[package]
name = "typebit"
version = "0.1.3"
edition = "2021"
license-file = "LICENSE"
authors = ["blueokanna, HyphenTeam"]
description = "TypeBit: A universal download engine for torrent (v1/v2, DHT, PEX, web seeds), eD2k/eMule, Xunlei, FlashGet, QQDL, IPFS, Kad and direct HTTP(S)/FTP, with provable-download receipts and a semantic utility scheduler."
homepage = "https://github.com/blueokanna/TypeBit"
repository = "https://github.com/blueokanna/TypeBit"
readme = "README.md"
keywords = ["bittorrent", "p2p", "rust-core", "ed2k", "downloader"]
categories = [
    "network-programming",
    "cryptography",
    "web-programming::http-client",
]
include = ["src/**", "README.md", "LICENSE", "docs/**", "examples/**"]

[lib]
name = "typebit"
path = "src/lib.rs"

[dependencies]
nextjson = { version = "0.1", default-features = false, features = ["derive"] }
rustbinary = { version = "0.1.7", default-features = false, features = [
    "alloc",
] }
tzcraft = { version = "0.1", default-features = false }
courierust = { version = "1.0", default-features = false }
socket2 = { version = "0.6.5", optional = true }

[features]
default = []
std = ["nextjson/std", "tzcraft/std", "courierust/std", "socket2"]
ffi = ["std"]

[[example]]
name = "ffi_demo"
required-features = ["ffi"]

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
