[package]
name = "typebit-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[lib]
name = "typebit_core"
path = "src/lib.rs"

[dependencies]
nextjson = { workspace = true }
rustbinary = { workspace = true }
tzcraft = { workspace = true }
courierust = { workspace = true }

[features]
default = []
std = ["nextjson/std", "tzcraft/std", "courierust/std"]

[dev-dependencies]
